baseURL = "https://mcai4gl2.github.io/"
languageCode = "en-us"
title = "Blog of Random things"
theme = "diary"

[[menu.main]]
url = "/computers"
name = "Hardware"
weight = 1

[[menu.main]]
url = "/softwares"
name = "Software"
weight = 2

[[menu.main]]
url = "/trading"
name = "Trading"
weight = 3

[[menu.main]]
url = "/others"
name = "Others"
weight = 4
