baseURL = "https://mcai4gl2.github.io/"
languageCode = "en-us"
title = "Blog of Random things"
theme = "diary"

[[menu.main]]
url = "/computers"
name = "Hardware"
weight = 1

[[menu.main]]
url = "/others"
name = "Others"
weight = 2
